  // Import the mongoose library to define the appointment data structure
  const mongoose = require("mongoose");

  /**
   * Consultation Schema Definition
   * Purpose: Manages appointment scheduling and clinical records between patients and doctors
   * It links specific medical sessions with the user's health history and ML results
   */
  const ConsultationSchema = new mongoose.Schema({
    /**
     * Patient Linking
     * Connects this appointment to a specific User ID in the database
     */
    userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    
    // Basic patient details for the doctor's immediate reference
    name: String,
    age: Number,
    gender: String,
    
    /**
     * Diagnostic Context
     * Captures the results previously generated by the "Brain" (ML Server)
     * This includes the inherent Prakriti, predicted Dosha, and potential Disease
     */
    prakriti: String,         
    predictedDosha: String,   
    predictedDisease: String, 
    symptoms: String,         
    
    // Stores the local file path for any health reports uploaded during booking
    reportFile: String, 
    
    /**
     * Logistics
     * Defines which doctor is being consulted and the specific time/date of the meeting
     */
    practitioner: { type: String, required: true },
    date: { type: String, required: true }, 
    time: { type: String, required: true }, 
    
    /**
     * Appointment Lifecycle
     * Tracks the state of the booking from initial reservation to completion
     */
    status: { 
      type: String, 
      enum: ["Reserved", "Confirmed", "Rejected", "Completed"], 
      default: "Reserved" 
    },
    
    /**
     * Clinical Recommendations
     * Fields updated by the doctor after the consultation is finished
     */
    medicines: { type: String, default: "" },
    lifestyle: { type: String, default: "" },
    notes: { type: String, default: "" },
    
    // Automatically captures the timestamp of the booking creation
    createdAt: { type: Date, default: Date.now }
  });

  /**
   * Time To Live (TTL) Index
   * Purpose: Automatically deletes "Reserved" slots after 24 hours (86400 seconds)
   * This prevents unconfirmed bookings from permanently clogging the doctor's schedule
   */
  ConsultationSchema.index(
    { createdAt: 1 }, 
    { 
      expireAfterSeconds: 86400, 
      partialFilterExpression: { status: "Reserved" } 
    }
  );

  /**
   * Export the Consultation model
   * Used by the backend "Manager" to handle scheduling and practitioner dashboards
   */
  module.exports = mongoose.model("Consultation", ConsultationSchema);